apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: usb-storage-class
provisioner: cluster.local/local-path-provisioner
parameters:
  nodePath: /data
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
