################################
### Secrets Repository
################################

apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  secretRef:
    name: secrets-repo-ssh
  url: ssh://git@github.com/Strayfe/home-server-secrets

---

################################
### Secrets Manifest
################################

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: secrets
  path: ./
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
